import os
import yaml
from decouple import config as env

LETTERS_MAPPER = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'h', 'ґ': 'g', 'д': 'd', 'е': 'e', 'є': 'ye', 'ж': 'zh',
                  'з': 'z', 'и': 'y', 'і': 'i', 'ї': 'yi', 'й': 'j', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n',
                  'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c',
                  'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ь': "'", 'ю': 'ju', 'я': 'ja'}


def translit(text):
    result = ''
    for char in text:
        letter = LETTERS_MAPPER.get(char.lower(), char)
        if char.isupper():
            letter = letter.upper()
        result += letter
    return result


def read_config(file_path):
    with open(file_path, 'r') as file:
        return yaml.safe_load(file)


def generate_css(config, output_path):
    css_content = "/* This file was automatically generated by server/generate_static.py */\n"
    for service in config['services']:
        for key, value in service.items():
            name = translit(key.lower())
            css_content += f".info-{name} " + "{\n" + f"    color: {value['color']};\n" + "}\n"
            css_content += f".bullet.service_{name} " + "{\n" + f"    color: {value['color']};\n" + "}\n"
        css_content += "\n"
    with open(output_path, 'w') as file:
        file.write(css_content)
    print(f"file saved: {output_path}")


def generate_js(config, output_path):
    js_content = "// this file was automatically generated by server/generate_static.py\n"
    services_const = "export const SERVICES = {\n"
    mapper_const = "export const SERVICE_TO_NUMBER = {\n"
    for (i, service) in enumerate(config['services']):
        services_const += f"    {i + 1}: " + "{\n"
        for key, value in service.items():
            name = translit(key.lower())
            mapper_const += f'    "{name.upper()}": {i + 1},\n'
            title = value['title']
            services_const += f'     name: "{title}",\n'
            services_const += f'     icon: "{name}",\n'
        services_const += "  },\n"
    mapper_const += "};\n"
    services_const += "};\n"

    categories_const = "export const CATEGORIES = {\n"
    for (i, category) in enumerate(config['categories']):
        categories_const += f'    {translit(category).upper()}: "{translit(category)}",\n'
    categories_const += "};\n"

    js_content += services_const + "\n" + mapper_const + "\n" + categories_const
    print(os.getcwd())
    with open(output_path, 'w') as file:
        file.write(js_content)
    print(f"file saved: {output_path}")


cfg = read_config('config.yaml')
print(f'Generating css in {os.getcwd()}...')
generate_css(cfg, os.path.join(env('OUT_PATH', 'shared'), 'generated.css'))
print('Generating js... ')
generate_js(cfg, os.path.join(env('OUT_PATH', 'shared'), 'generated_constants.js'))

print('Static generated successfully!  ')
